### PR TITLE
Add alternative for compiling nginx with libressl

### PR DESCRIPTION
**Pull request by thelittlefireman**
#78

### CODE REVIEW

**Comment by thelittlefireman** [comment]
```
bash-5.0# nginx -V
nginx version: nginx/1.18.0
built by gcc 9.3.0 (Alpine 9.3.0) 
built with LibreSSL 3.3.1
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --with-perl_modules_path=/usr/lib/perl5/vendor_perl --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-Os' --with-ld-opt=-Wl,--as-needed --with-openssl=/tmp/libressl-3.3.1

```

**Comment by thelittlefireman** [comment]
@bunkerity do you need help for this pr ?

**Comment by bunkerity** [comment]
Hey @thelittlefireman,

Yes, it needs some modification to reflect the current Dockerfile like : removing crowdsec/install.sh, adding prepare.sh, new volumes, ...

**Comment by fl0ppy-d1sk** [comment]
Hey @thelittlefireman,

Too many changes since the current version. Maybe you can open an issue about it @thelittlefireman so we can add that feature to the next major update (1.5.X) ?

**Pull request closed without merging**
